<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Enable XML documentation file generation so DocFX can include API XML comments -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Suppress warnings about missing XML comments (CS1591) -->
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.3.2" />
    <PackageReference Include="CSharpFunctionalExtensions" Version="2.42.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
  </ItemGroup>

</Project>
