export const createConnectionRequestConst = {
  pageTitle: "Создание заявки на подключение",
  signInRequiredTitle: "Требуется вход",
  signInRequiredDescription: "Войдите, чтобы создать заявку на подключение.",
  signInLinkText: "Войти",
  loadingApplicantPartiesText: "Загружаем сохранённых заявителей...",
  applicantPartiesErrorText: "Не удалось загрузить сохранённых заявителей.",
  formTitle: "Заявка на подключение",
  applicantContextLegend: "Данные заявителя",
  existingApplicantOptionLabel: "Использовать сохранённого заявителя",
  newApplicantOptionLabel: "Ввести новые данные заявителя",
  savedApplicantSelectLabel: "Сохранённый заявитель",
  savedApplicantSelectPlaceholder: "Выберите сохранённого заявителя",
  noSavedApplicantPartiesText: "Сохранённых заявителей пока нет.",
  currentDefaultMarker: "Текущий",
  newApplicantFieldsTitle: "Новые данные заявителя",
  requestDetailsLabel: "Описание заявки",
  requestDetailsPlaceholder: "Опишите заявку на подключение",
  postalCodeLabel: "Почтовый индекс",
  regionLabel: "Регион",
  cityLabel: "Город",
  streetLabel: "Улица",
  houseLabel: "Дом",
  buildingLabel: "Корпус",
  apartmentLabel: "Квартира",
  firstNameLabel: "Имя",
  middleNameLabel: "Отчество",
  lastNameLabel: "Фамилия",
  emailLabel: "Email заявителя",
  phoneNumberLabel: "Телефон",
  submitButtonText: "Создать заявку",
  submittingButtonText: "Создаём заявку...",
  requiredSuffix: ": заполните поле.",
  invalidEmailMessage: "Email заявителя указан неверно.",
  invalidPhoneMessage: "Телефон указан неверно.",
  rootErrorFallback: "Не удалось создать заявку.",
  existingApplicantRequired:
    "Выберите сохранённого заявителя или введите новые данные заявителя.",
} as const;
