export const createConnectionRequestConst = {
  pageTitle: "Create connection request",
  signInRequiredTitle: "Sign in required",
  signInRequiredDescription: "Sign in to create a connection request.",
  signInLinkText: "Login",
  loadingApplicantPartiesText: "Loading saved Applicant Parties...",
  applicantPartiesErrorText: "Saved Applicant Parties could not be loaded.",
  formTitle: "Connection request",
  applicantContextLegend: "Applicant context",
  existingApplicantOptionLabel: "Use saved Applicant Party",
  newApplicantOptionLabel: "Enter new applicant data",
  savedApplicantSelectLabel: "Saved Applicant Party",
  savedApplicantSelectPlaceholder: "Choose saved Applicant Party",
  noSavedApplicantPartiesText: "No saved Applicant Parties are available yet.",
  currentDefaultMarker: "Current/default",
  newApplicantFieldsTitle: "New applicant data",
  requestDetailsLabel: "Request details",
  requestDetailsPlaceholder: "Describe the connection request",
  postalCodeLabel: "Postal code",
  regionLabel: "Region",
  cityLabel: "City",
  streetLabel: "Street",
  houseLabel: "House",
  buildingLabel: "Building",
  apartmentLabel: "Apartment",
  firstNameLabel: "First name",
  middleNameLabel: "Middle name",
  lastNameLabel: "Last name",
  emailLabel: "Applicant email",
  phoneNumberLabel: "Phone number",
  submitButtonText: "Create request",
  submittingButtonText: "Creating request...",
  requiredSuffix: " is required.",
  invalidEmailMessage: "Applicant email is invalid.",
  invalidPhoneMessage: "Phone number is invalid.",
  rootErrorFallback: "Request could not be created.",
  existingApplicantRequired: "Choose a saved Applicant Party or enter new applicant data.",
} as const;
