export const agreementExchangeDetailsConst = {
  statusLabel: "Статус обмена",
  actorSideLabel: "Текущая сторона",
  requestSummaryTitle: "Сводка заявки",
  activeProposalTitle: "Активное предложение",
  proposalHistoryTitle: "История предложений",
  documentTitle: "Документ",
  downloadDocumentLinkText: "Скачать документ",
  unknownDocumentFileName: "документ договора",
  exchangeTitlePrefix: "Обмен",
  senderLabel: "Автор",
  stateLabel: "Состояние",
  createdAtLabel: "Создан",
  lastActivityAtLabel: "Последняя активность",
  requestLabel: "Заявка",
  requestStatusLabel: "Статус заявки",
  objectAddressLabel: "Адрес объекта",
  noActiveProposalText: "Активного предложения нет.",
  noProposalHistoryText: "Версий предложения пока нет.",
  actionsRegionTitle: "Доступные действия по обмену",
} as const;
