// <auto-generated />
using System;
using EnergyManagement.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223131949_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("bigint")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.ClientRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTimeOffset>("RequestDateTime")
                        .HasMaxLength(100)
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RequestDateTime");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("RequestDetails");

                    b.Property<int>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("RequestType");

                    b.HasKey("Id");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator<string>("ClientTypeDiscriminator").HasValue("ClientRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.RequestReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("ReviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Commentary")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("ReviewCommentary");

                    b.Property<bool>("IsApproved")
                        .HasMaxLength(50)
                        .HasColumnType("bit")
                        .HasColumnName("IsApproved");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("RequestId");

                    b.Property<DateTimeOffset>("ReviewDateTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ReviewTime");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestReviews", (string)null);
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.HasBaseType("Client");

                    b.ToTable("IndividualClients", (string)null);
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.IndividualRequest", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.DocumentManaging.ClientRequest");

                    b.Property<long?>("IdividualClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IndividualClientId")
                        .HasColumnType("bigint");

                    b.HasIndex("IdividualClientId");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator().HasValue("IndividualClientRequest");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.OwnsOne("Email", "Email", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("Password", "_password", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Hash")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("_password");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.RequestReview", b =>
                {
                    b.HasOne("Domain.EnergyManagement.DocumentManaging.Manager", "Manager")
                        .WithMany("RequestReviews")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EnergyManagement.DocumentManaging.ClientRequest", null)
                        .WithMany("Reviews")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.HasOne("Client", null)
                        .WithOne()
                        .HasForeignKey("IndividualClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FullName", "_fullName", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.OwnsOne("PassportData", "_passportData", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<DateOnly?>("IssuedAtTime")
                                .HasMaxLength(50)
                                .HasColumnType("date")
                                .HasColumnName("IssuedAt");

                            b1.Property<string>("IssuedBy")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IssuedBy");

                            b1.Property<string>("Number")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Number");

                            b1.Property<string>("Series")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Series");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.OwnsOne("PhoneNumber", "_phoneNumber", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.Navigation("_fullName");

                    b.Navigation("_passportData");

                    b.Navigation("_phoneNumber");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.IndividualRequest", b =>
                {
                    b.HasOne("IndividualClient", "Client")
                        .WithMany("ClientRequests")
                        .HasForeignKey("IdividualClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.Address", "Address", b1 =>
                        {
                            b1.Property<long>("IndividualRequestId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("House");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Street");

                            b1.Property<string>("_apartment")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Apartment");

                            b1.Property<string>("_building")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Building");

                            b1.HasKey("IndividualRequestId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("IndividualRequestId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.ClientRequest", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.Manager", b =>
                {
                    b.Navigation("RequestReviews");
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.Navigation("ClientRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
