// <auto-generated />
using System;
using EnergyManagement.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221132816_da")]
    partial class da
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("bigint")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.ClientRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTimeOffset>("RequestDateTime")
                        .HasMaxLength(100)
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RequestDateTime");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("RequestDetails");

                    b.Property<int>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("RequestType");

                    b.HasKey("Id");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator<string>("ClientTypeDiscriminator").HasValue("ClientRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.RequestReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("ReviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Commentary")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("ReviewCommentary");

                    b.Property<bool>("IsApproved")
                        .HasMaxLength(50)
                        .HasColumnType("bit")
                        .HasColumnName("IsApproved");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("RequestId");

                    b.Property<DateTimeOffset>("ReviewDateTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ReviewTime");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestReviews", (string)null);
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.HasBaseType("Client");

                    b.ToTable("IndividualClients", (string)null);
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.IndividualRequest", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.DocumentManaging.ClientRequest");

                    b.Property<long?>("IdividualClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IndividualClientId")
                        .HasColumnType("bigint");

                    b.HasIndex("IdividualClientId");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator().HasValue("IndividualClientRequest");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.RequestReview", b =>
                {
                    b.HasOne("Domain.EnergyManagement.DocumentManaging.Manager", "Manager")
                        .WithMany("RequestReviews")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EnergyManagement.DocumentManaging.ClientRequest", null)
                        .WithMany("Reviews")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.HasOne("Client", null)
                        .WithOne()
                        .HasForeignKey("IndividualClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FullName", "_fullName", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.OwnsOne("PassportData", "_passportData", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<DateOnly>("IssuedAtTime")
                                .HasMaxLength(50)
                                .HasColumnType("date")
                                .HasColumnName("IssuedAt");

                            b1.Property<string>("IssuedBy")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IssuedBy");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Number");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Series");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.OwnsOne("PhoneNumber", "_phoneNumber", b1 =>
                        {
                            b1.Property<long>("IndividualClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("IndividualClientId");

                            b1.ToTable("IndividualClients");

                            b1.WithOwner()
                                .HasForeignKey("IndividualClientId");
                        });

                    b.Navigation("_fullName")
                        .IsRequired();

                    b.Navigation("_passportData")
                        .IsRequired();

                    b.Navigation("_phoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.IndividualRequest", b =>
                {
                    b.HasOne("IndividualClient", "Client")
                        .WithMany("ClientRequests")
                        .HasForeignKey("IdividualClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.ClientRequest", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.EnergyManagement.DocumentManaging.Manager", b =>
                {
                    b.Navigation("RequestReviews");
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.Navigation("ClientRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
