// <auto-generated />
using EnergyManagement.Server.L1.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyManagement.Server.Migrations.L1Db
{
    [DbContext(typeof(L1DbContext))]
    [Migration("20260518133000_AddClientAccountIdToL1ClientRequests")]
    partial class AddClientAccountIdToL1ClientRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
