// <auto-generated />
using System;
using EnergyManagement.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyManagement.Server.Migrations.L1Db
{
    [DbContext(typeof(EnergyManagementDbContext))]
    [Migration("20260605123216_TuneDomainFieldMaxLengths")]
    partial class TuneDomainFieldMaxLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.EnergyManagement.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("L1Accounts", (string)null);

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.AgreementProposalExchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveProposalVersion")
                        .HasColumnType("int")
                        .HasColumnName("ActiveProposalVersion");

                    b.Property<long>("ClientAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientAccountId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset?>("FinalRefusedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FinalRefusedAt");

                    b.Property<long?>("FinalRefusedByEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("FinalRefusedByEmployeeId");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequestId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId");

                    b.HasIndex("RequestId");

                    b.ToTable("L1AgreementProposalExchanges", (string)null);
                });

            modelBuilder.Entity("Domain.EnergyManagement.ApplicantParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicantPartyDiscriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("ApplicantPartyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ApplicantPartyType");

                    b.Property<long>("ClientAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientAccountId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsCurrentActiveVersion")
                        .HasColumnType("bit")
                        .HasColumnName("IsCurrentActiveVersion");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VerificationStatus");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId");

                    b.ToTable("L1ApplicantParties", (string)null);

                    b.HasDiscriminator<string>("ApplicantPartyDiscriminator").HasValue("ApplicantParty");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.ClientRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicantPartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("ApplicantPartyId");

                    b.Property<long>("ClientAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientAccountId");

                    b.Property<string>("ClientRequestDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("Details");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RequestType");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantPartyId");

                    b.HasIndex("ClientAccountId");

                    b.ToTable("L1ClientRequests", (string)null);

                    b.HasDiscriminator<string>("ClientRequestDiscriminator").HasValue("ClientRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.EnergyManagement.ClientAccount", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.Account");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Domain.EnergyManagement.Employee", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.Account");

                    b.Property<string>("WindowsLogin")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("WindowsLogin");

                    b.HasIndex("WindowsLogin")
                        .IsUnique()
                        .HasFilter("[WindowsLogin] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Domain.EnergyManagement.IndividualApplicantParty", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.ApplicantParty");

                    b.HasDiscriminator().HasValue("Individual");
                });

            modelBuilder.Entity("Domain.EnergyManagement.IndividualEntrepreneurApplicantParty", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.ApplicantParty");

                    b.HasDiscriminator().HasValue("IndividualEntrepreneur");
                });

            modelBuilder.Entity("Domain.EnergyManagement.LegalEntityApplicantParty", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.ApplicantParty");

                    b.HasDiscriminator().HasValue("LegalEntity");
                });

            modelBuilder.Entity("Domain.EnergyManagement.ConnectionRequest", b =>
                {
                    b.HasBaseType("Domain.EnergyManagement.ClientRequest");

                    b.HasDiscriminator().HasValue("Connection");
                });

            modelBuilder.Entity("Domain.EnergyManagement.Account", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.Email", "Email", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("AccountId");

                            b1.ToTable("L1Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.AgreementProposalExchange", b =>
                {
                    b.HasOne("Domain.EnergyManagement.ClientRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.EnergyManagement.AgreementProposal", "Proposals", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("Id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("AgreementProposalExchangeId")
                                .HasColumnType("bigint")
                                .HasColumnName("AgreementProposalExchangeId");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("State");

                            b1.Property<int>("Version")
                                .HasColumnType("int")
                                .HasColumnName("Version");

                            b1.HasKey("Id");

                            b1.HasIndex("AgreementProposalExchangeId");

                            b1.ToTable("L1AgreementProposals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgreementProposalExchangeId");

                            b1.OwnsOne("Domain.EnergyManagement.AgreementDocumentRef", "Document", b2 =>
                                {
                                    b2.Property<long>("AgreementProposalId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("DocumentContentType");

                                    b2.Property<string>("OriginalFileName")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("nvarchar(255)")
                                        .HasColumnName("DocumentOriginalFileName");

                                    b2.Property<long>("SizeBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("DocumentSizeBytes");

                                    b2.Property<string>("StorageKey")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("DocumentStorageKey");

                                    b2.HasKey("AgreementProposalId");

                                    b2.ToTable("L1AgreementProposals");

                                    b2.WithOwner()
                                        .HasForeignKey("AgreementProposalId");
                                });

                            b1.OwnsOne("Domain.EnergyManagement.AgreementProposalAuthor", "Author", b2 =>
                                {
                                    b2.Property<long>("AgreementProposalId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Sender")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Sender");

                                    b2.Property<long>("SenderId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("SenderId");

                                    b2.HasKey("AgreementProposalId");

                                    b2.ToTable("L1AgreementProposals");

                                    b2.WithOwner()
                                        .HasForeignKey("AgreementProposalId");
                                });

                            b1.OwnsOne("Domain.EnergyManagement.ProposalComment", "Comment", b2 =>
                                {
                                    b2.Property<long>("AgreementProposalId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("Comment");

                                    b2.HasKey("AgreementProposalId");

                                    b2.ToTable("L1AgreementProposals");

                                    b2.WithOwner()
                                        .HasForeignKey("AgreementProposalId");
                                });

                            b1.Navigation("Author")
                                .IsRequired();

                            b1.Navigation("Comment");

                            b1.Navigation("Document")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.EnergyManagement.FinalRefusalReason", "FinalRefusalReason", b1 =>
                        {
                            b1.Property<long>("AgreementProposalExchangeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("FinalRefusalReason");

                            b1.HasKey("AgreementProposalExchangeId");

                            b1.ToTable("L1AgreementProposalExchanges");

                            b1.WithOwner()
                                .HasForeignKey("AgreementProposalExchangeId");
                        });

                    b.Navigation("FinalRefusalReason");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Domain.EnergyManagement.ApplicantParty", b =>
                {
                    b.HasOne("Domain.EnergyManagement.ClientAccount", null)
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.Email", "Email", b1 =>
                        {
                            b1.Property<long>("ApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("ApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<long>("ApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("ApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantPartyId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.ClientRequest", b =>
                {
                    b.HasOne("Domain.EnergyManagement.ApplicantParty", null)
                        .WithMany()
                        .HasForeignKey("ApplicantPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.EnergyManagement.ClientAccount", null)
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.Address", "ObjectAddress", b1 =>
                        {
                            b1.Property<long>("ClientRequestId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_City");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_House");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("ObjectAddress_PostalCode");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_Region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_Street");

                            b1.Property<string>("_apartment")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_Apartment");

                            b1.Property<string>("_building")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ObjectAddress_Building");

                            b1.HasKey("ClientRequestId");

                            b1.ToTable("L1ClientRequests");

                            b1.WithOwner()
                                .HasForeignKey("ClientRequestId");
                        });

                    b.Navigation("ObjectAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.Employee", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("EmployeeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EmployeeFullName_FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EmployeeFullName_LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EmployeeFullName_MiddleName");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("L1Accounts");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.IndividualApplicantParty", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("IndividualApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FullName_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FullName_LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FullName_MiddleName");

                            b1.HasKey("IndividualApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("IndividualApplicantPartyId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.IndividualEntrepreneurApplicantParty", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.DocumentManaging.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("IndividualEntrepreneurApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IndividualEntrepreneurFullName_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IndividualEntrepreneurFullName_LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IndividualEntrepreneurFullName_MiddleName");

                            b1.HasKey("IndividualEntrepreneurApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.Inn", "Inn", b1 =>
                        {
                            b1.Property<long>("IndividualEntrepreneurApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("IndividualEntrepreneur_Inn");

                            b1.HasKey("IndividualEntrepreneurApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.Ogrnip", "Ogrnip", b1 =>
                        {
                            b1.Property<long>("IndividualEntrepreneurApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("IndividualEntrepreneur_Ogrnip");

                            b1.HasKey("IndividualEntrepreneurApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurApplicantPartyId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Inn")
                        .IsRequired();

                    b.Navigation("Ogrnip")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.LegalEntityApplicantParty", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.Kpp", "Kpp", b1 =>
                        {
                            b1.Property<long>("LegalEntityApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("nvarchar(9)")
                                .HasColumnName("LegalEntity_Kpp");

                            b1.HasKey("LegalEntityApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.Inn", "Inn", b1 =>
                        {
                            b1.Property<long>("LegalEntityApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("LegalEntity_Inn");

                            b1.HasKey("LegalEntityApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.Ogrn", "Ogrn", b1 =>
                        {
                            b1.Property<long>("LegalEntityApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("nvarchar(13)")
                                .HasColumnName("LegalEntity_Ogrn");

                            b1.HasKey("LegalEntityApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityApplicantPartyId");
                        });

                    b.OwnsOne("Domain.EnergyManagement.OrganizationName", "OrganizationName", b1 =>
                        {
                            b1.Property<long>("LegalEntityApplicantPartyId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("LegalEntity_OrganizationName");

                            b1.HasKey("LegalEntityApplicantPartyId");

                            b1.ToTable("L1ApplicantParties");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityApplicantPartyId");
                        });

                    b.Navigation("Inn")
                        .IsRequired();

                    b.Navigation("Kpp")
                        .IsRequired();

                    b.Navigation("Ogrn")
                        .IsRequired();

                    b.Navigation("OrganizationName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnergyManagement.ConnectionRequest", b =>
                {
                    b.OwnsOne("Domain.EnergyManagement.RequestReview", "Review", b1 =>
                        {
                            b1.Property<long>("RequestId")
                                .HasColumnType("bigint")
                                .HasColumnName("RequestId");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CompletedAt");

                            b1.Property<long?>("CompletedByEmployeeId")
                                .HasColumnType("bigint")
                                .HasColumnName("CompletedByEmployeeId");

                            b1.Property<DateTimeOffset>("StartedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("StartedAt");

                            b1.Property<long>("StartedByEmployeeId")
                                .HasColumnType("bigint")
                                .HasColumnName("StartedByEmployeeId");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Status");

                            b1.HasKey("RequestId");

                            b1.ToTable("L1RequestReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Domain.EnergyManagement.RejectionFeedback", "RejectionFeedback", b2 =>
                                {
                                    b2.Property<long>("RequestReviewRequestId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)")
                                        .HasColumnName("RejectionReason");

                                    b2.HasKey("RequestReviewRequestId");

                                    b2.ToTable("L1RequestReviews");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestReviewRequestId");
                                });

                            b1.Navigation("RejectionFeedback");
                        });

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
