export const employeeRequestDashboardConst = {
  pageTitle: "Employee Request Dashboard",
  pageDescription:
    "Review-relevant requests visible to the current Employee.",
  loadingText: "Loading employee requests...",
  errorText: "Could not load employee requests.",
  signInRequiredTitle: "Sign in as Employee to view request dashboard",
  signInRequiredDescription:
    "Employee request dashboard is available only to authenticated Employee accounts.",
  signInLinkText: "Sign in",
  accessDeniedTitle: "Employee access required",
  accessDeniedDescription:
    "This dashboard is for Employee review work. Use an Employee account to continue.",
  emptyTitle: "No employee requests to review.",
  emptyDescription: "Review-relevant requests will appear here.",
  filteredEmptyTitle: "No employee requests match selected filters.",
  filteredEmptyDescription:
    "Change or reset filters to see other employee requests.",
  filteredEmptyResetText: "Reset filters",
  listLabel: "Employee request dashboard list",
  requestTitlePrefix: "Request",
  requestTypeLabel: "Request type",
  statusLabel: "Status",
  createdAtLabel: "Created at",
  applicantLabel: "Applicant",
  objectAddressLabel: "Object address",
  reviewStateLabel: "Review state",
  detailsLinkText: "Open employee details",
  filtersTitle: "Dashboard filters",
  statusFilterLabel: "Status",
  reviewStateFilterLabel: "Review state",
  allStatusesOption: "All statuses",
  allReviewStatesOption: "All review states",
  resetFiltersText: "Reset filters",
  invalidFiltersResetText: "Reset filters",
  unknownValue: "—",
  reviewStateLabels: {
    NotStarted: "Not started",
    StartedByCurrentEmployee: "Started by current Employee",
    StartedByAnotherEmployee: "Started by another Employee",
    Approved: "Approved",
    Rejected: "Rejected",
  },
} as const;
