export const employeeRequestDashboardConst = {
  pageTitle: "Заявки на рассмотрение",
  pageDescription: "Заявки, доступные текущему сотруднику для рассмотрения.",
  loadingText: "Загружаем заявки...",
  errorText: "Не удалось загрузить заявки.",
  signInRequiredTitle: "Войдите как сотрудник, чтобы открыть список заявок",
  signInRequiredDescription:
    "Список заявок доступен только авторизованным сотрудникам.",
  signInLinkText: "Войти",
  accessDeniedTitle: "Требуется доступ сотрудника",
  accessDeniedDescription:
    "Этот раздел предназначен для рассмотрения заявок сотрудниками.",
  emptyTitle: "Нет заявок для рассмотрения.",
  emptyDescription: "Заявки для рассмотрения появятся здесь.",
  filteredEmptyTitle: "Нет заявок по выбранным фильтрам.",
  filteredEmptyDescription: "Измените или сбросьте фильтры, чтобы увидеть заявки.",
  filteredEmptyResetText: "Сбросить фильтры",
  listLabel: "Список заявок на рассмотрение",
  requestTitlePrefix: "Заявка",
  requestTypeLabel: "Тип заявки",
  statusLabel: "Статус",
  createdAtLabel: "Создана",
  applicantLabel: "Заявитель",
  objectAddressLabel: "Адрес объекта",
  reviewStateLabel: "Состояние рассмотрения",
  detailsLinkText: "Открыть детали",
  filtersTitle: "Фильтры заявок",
  statusFilterLabel: "Статус",
  reviewStateFilterLabel: "Состояние рассмотрения",
  allStatusesOption: "Все статусы",
  allReviewStatesOption: "Все состояния",
  resetFiltersText: "Сбросить фильтры",
  invalidFiltersResetText: "Сбросить фильтры",
  unknownValue: "—",
  reviewStateLabels: {
    NotStarted: "Не начато",
    StartedByCurrentEmployee: "Рассматривается вами",
    StartedByAnotherEmployee: "Рассматривается другим сотрудником",
    Approved: "Одобрена",
    Rejected: "Отклонена",
  },
  statusLabels: {
    InReview: "На рассмотрении",
    Approved: "Одобрена",
    Rejected: "Отклонена",
    AgreementExchangeFailed: "Согласование договора не завершено",
  },
  requestTypeLabels: {
    Connection: "Подключение",
  },
} as const;
