export const employeeRequestDetailsConst = {
  pageTitle: "Рассмотрение заявки",
  loadingText: "Загружаем детали заявки...",
  errorText: "Не удалось загрузить детали заявки.",
  notFoundTitle: "Детали заявки не найдены.",
  notFoundDescription:
    "Заявка может не существовать или быть недоступной текущему сотруднику.",
  signInRequiredTitle: "Войдите как сотрудник, чтобы открыть детали заявки",
  signInRequiredDescription:
    "Детали заявки доступны только авторизованным сотрудникам.",
  signInLinkText: "Войти",
  accessDeniedTitle: "Требуется доступ сотрудника",
  accessDeniedDescription: "Детали заявки доступны только сотрудникам.",
  backToDashboardText: "Вернуться к списку заявок",
  requestTitlePrefix: "Заявка",
  requestDataTitle: "Данные заявки",
  applicantTitle: "Данные заявителя",
  reviewStateTitle: "Состояние рассмотрения",
  actionAvailabilityTitle: "Доступные действия",
  agreementExchangeTitle: "Договорной обмен",
  requestTypeLabel: "Тип заявки",
  statusLabel: "Статус",
  createdAtLabel: "Создана",
  objectAddressLabel: "Адрес объекта",
  detailsLabel: "Описание заявки",
  applicantNameLabel: "Заявитель",
  applicantTypeLabel: "Тип заявителя",
  applicantEmailLabel: "Email",
  applicantPhoneLabel: "Телефон",
  startReviewAvailable: "Можно начать рассмотрение.",
  startReviewBlocked: "Начать рассмотрение сейчас нельзя.",
  approveAvailable:
    "Одобрение доступно после начала рассмотрения текущим сотрудником.",
  approveBlocked: "Одобрение недоступно.",
  rejectAvailable:
    "Отклонение доступно после начала рассмотрения текущим сотрудником.",
  rejectBlocked: "Отклонение недоступно.",
  unknownValue: "—",
  reviewStateLabels: {
    NotStarted: "Не начато",
    StartedByCurrentEmployee: "Рассматривается вами",
    StartedByAnotherEmployee: "Рассматривается другим сотрудником",
    Approved: "Одобрена",
    Rejected: "Отклонена",
  },
  statusLabels: {
    InReview: "На рассмотрении",
    Approved: "Одобрена",
    Rejected: "Отклонена",
    AgreementExchangeFailed: "Договорной обмен не завершён",
  },
  requestTypeLabels: {
    Connection: "Подключение",
  },
  applicantTypeLabels: {
    Individual: "Физическое лицо",
  },
} as const;
