export const employeeRequestDetailsConst = {
  pageTitle: "Employee Request Details",
  loadingText: "Loading employee request details...",
  errorText: "Could not load employee request details.",
  notFoundTitle: "Employee request details not found.",
  notFoundDescription:
    "The request may not exist or may not be available to the current Employee.",
  signInRequiredTitle: "Sign in as Employee to view request details",
  signInRequiredDescription:
    "Employee request details are available only to authenticated Employee accounts.",
  signInLinkText: "Sign in",
  accessDeniedTitle: "Employee access required",
  accessDeniedDescription:
    "Employee request details are available only to Employee accounts.",
  backToDashboardText: "Back to Employee dashboard",
  requestTitlePrefix: "Request",
  requestDataTitle: "Request data",
  applicantTitle: "Applicant / client data",
  reviewStateTitle: "Review state",
  actionAvailabilityTitle: "Review action availability",
  requestTypeLabel: "Request type",
  statusLabel: "Status",
  createdAtLabel: "Created at",
  objectAddressLabel: "Object address",
  detailsLabel: "Request details",
  applicantNameLabel: "Applicant",
  applicantTypeLabel: "Applicant type",
  applicantEmailLabel: "Email",
  applicantPhoneLabel: "Phone number",
  startReviewAvailable: "Start review is available.",
  startReviewBlocked: "Start review is not available.",
  approveAvailable: "Approve is available after review is started by current Employee.",
  approveBlocked: "Approve is not available.",
  rejectAvailable: "Reject is available after review is started by current Employee.",
  rejectBlocked: "Reject is not available.",
  unknownValue: "—",
  reviewStateLabels: {
    NotStarted: "Not started",
    StartedByCurrentEmployee: "Started by current Employee",
    StartedByAnotherEmployee: "Started by another Employee",
    Approved: "Approved",
    Rejected: "Rejected",
  },
} as const;
