export const agreementExchangeListConst = {
  pageTitle: "Обмен договорными предложениями",
  pageDescription:
    "Здесь отображаются договорные обмены, доступные текущему пользователю.",
  loadingText: "Загружаем договорные обмены...",
  errorText: "Не удалось загрузить договорные обмены.",
  signInRequiredTitle: "Войдите, чтобы увидеть договорные обмены",
  signInRequiredDescription:
    "Список договорных обменов доступен только авторизованным пользователям.",
  signInLinkText: "Войти",
  emptyTitle: "Договорных обменов пока нет.",
  emptyDescription: "Когда появится договорный обмен, он будет показан здесь.",
  filteredEmptyTitle: "Обменов с выбранным статусом не найдено.",
  filteredEmptyDescription: "Измените или сбросьте фильтр, чтобы увидеть другие обмены.",
  filteredEmptyResetText: "Сбросить фильтр",
  statusFilterLabel: "Статус обмена",
  allStatusesOption: "Все статусы",
  resetFiltersText: "Сбросить фильтр",
  exchangeTitlePrefix: "Обмен",
  requestLabel: "Заявка",
  statusLabel: "Статус",
  activeVersionLabel: "Активная версия",
  activeSenderLabel: "Активная сторона",
  requestDisplayNameLabel: "Заявитель",
  objectAddressLabel: "Адрес объекта",
  createdAtLabel: "Создан",
  lastActivityAtLabel: "Последняя активность",
  detailsLinkText: "Открыть детали",
  unknownValue: "—",
} as const;
