export const applicantPartiesListConst = {
  title: "Заявители",
  currentDefaultsTitle: "Текущий заявитель",
  otherSavedTitle: "Другие сохранённые заявители",
  emptyTitle: "Сохранённых заявителей пока нет.",
  emptyDescription:
    "Сохранённые заявители появятся здесь после добавления к аккаунту.",
  currentDefaultBadge: "Текущий",
  applicantPartyTitlePrefix: "Заявитель",
  applicantPartyTypeLabel: "Тип заявителя",
  displayNameLabel: "Отображаемое имя",
  firstNameLabel: "Имя",
  middleNameLabel: "Отчество",
  lastNameLabel: "Фамилия",
  emailLabel: "Email заявителя",
  phoneNumberLabel: "Телефон",
  verificationStatusLabel: "Статус проверки",
  createdAtLabel: "Создан",
  unknownValue: "—",
} as const;
