export const headerConst = {
  homeLinkTextPart1: "Energy",
  homeLinkTextPart2: "Management",
  homeLinkSloganText: "Заявки и договоры в одном интерфейсе",
  loginLinkText: "Войти",
  registerLinkText: "Регистрация",
  logoutButtonText: "Выйти",
  logoutPendingButtonText: "Выходим...",
  accountLinkText: "Личный кабинет",
  createRequestLinkText: "Создать заявку",
  myRequestsLinkText: "Мои заявки",
  agreementExchangesLinkText: "Мои договоры",
  employeeRequestsLinkText: "Заявки Employee",
  employeeAgreementExchangesLinkText: "Договорные обмены",
  homeLinkText: "Главная",
  hotlinePhoneNumberText: "8-800-100-70-00",
  hotlinePhoneLabelText: "Поддержка",
} as const;
