export const headerConst = {
  homeLinkTextPart1: "Заринская сетевая",
  homeLinkTextPart2: "компания",
  homeLinkSloganText: "Мы делаем жизнь светлее",
  loginLinkText: "Войти",
  registerLinkText: "Регистрация",
  logoutButtonText: "Выйти",
  logoutPendingButtonText: "Выходим...",
  accountLinkText: "Личный кабинет",
  myRequestsLinkText: "Мои заявки",
  createRequestLinkText: "Создать заявку",
  employeeRequestsLinkText: "Заявки Employee",
  agreementExchangesLinkText: "Мои договоры",
  employeeAgreementExchangesLinkText: "Договорные обмены",
  internetReceptionLinkText: "Интернет-приемная",
  hotlinePhoneNumberText: "8-800-100-70-00",
  hotlinePhoneLabelText: "Телефон горячей линии:",

  homeLinkText: "Главная",
  aboutCompanyLinkText: "О компании",
  toCustomersLinkText: "Потребителям",
  disclosureInformationLinkText: "Раскрытие информации",
  procurementLinkText: "Закупки",
  vacanciesLinkText: "Вакансии",
} as const;
