export const headerConst = {
  homeLinkTextPart1: "ООО «ЗСК»",
  homeLinkTextPart2: "",
  sessionLoadingText: "Загружаем сессию...",
  homeLinkSloganText: "Заявки и договоры в одном интерфейсе",
  loginLinkText: "Войти",
  registerLinkText: "Регистрация",
  logoutButtonText: "Выйти",
  logoutPendingButtonText: "Выходим...",
  accountLinkText: "Личный кабинет",
  createRequestLinkText: "Создать заявку",
  myRequestsLinkText: "Мои заявки",
  agreementExchangesLinkText: "Мои договоры",
  employeeRequestsLinkText: "Заявки",
  employeeAgreementExchangesLinkText: "Согласование договоров",
  homeLinkText: "Главная",
  hotlinePhoneNumberText: "8-800-100-70-00",
  hotlinePhoneLabelText: "Поддержка",
} as const;
